<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_1              2              3</name>
   <tag></tag>
   <elementGuidId>bc6fd82d-6265-4919-aa9b-da47819761ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='star']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#star</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>684a8beb-b1d2-4c4e-b722-69f9ee170a6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>star</value>
      <webElementGuid>f264c4bf-42ed-41c5-8c4b-aa987d220acb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>star</value>
      <webElementGuid>8e88e999-f7fe-4593-9dae-5284a6f7cbde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>d3e1d0f2-8e84-4973-8f51-2ba1671d646c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
              1*
              2*
              3*
            </value>
      <webElementGuid>16255aee-8463-4bf7-9b2c-ff76341f055e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;star&quot;)</value>
      <webElementGuid>b63d8a02-2010-4662-bfeb-0d47dd0f764f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='star']</value>
      <webElementGuid>bdf92848-c67a-45fa-aba4-041d76340b45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmHotelOperator']/div/div[11]/div/select</value>
      <webElementGuid>57cc3f0f-bf2d-4cb2-bfd6-159a51c022ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hotel Type'])[1]/following::select[1]</value>
      <webElementGuid>cf1c845d-248a-4941-bd49-df788124ebd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Website'])[1]/following::select[1]</value>
      <webElementGuid>e467693a-3c16-43ea-8767-5ef8f680caf9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Other Details'])[1]/preceding::select[1]</value>
      <webElementGuid>42ea2a74-2660-4c94-9ace-c9ab6a9addd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/select</value>
      <webElementGuid>642d358a-3e2d-4880-9609-b542834bb745</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'star' and @name = 'star' and (text() = '
              1*
              2*
              3*
            ' or . = '
              1*
              2*
              3*
            ')]</value>
      <webElementGuid>8e41d982-d454-4a4a-8d83-46be9c5d1e0f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
